version: "3.7"

services:
  gatha-api:
    network_mode: host
    container_name: gatha-api
    image: gatha-api
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: yarn start
    depends_on:
      - gatha-db

  gatha-db:
    container_name: gatha-db
    network_mode: host
    image: neo4j:latest

