version: "3.7"

services:
  gatha-api:
    container_name: gatha-api
    ports:
      - "4000:4000"
    image: gatha-api
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: yarn start
    depends_on:
      - gatha-db

  gatha-db:
    container_name: gatha-db
    # If running on Apple M1, use neo4j/neo4j-arm64-experimental:4.1.0-arm64
    image: neo4j:latest
    ports:
      - "7687:7687"
      - "7474:7474"
