version: "3.8"

services:
  gatha.api:
    container_name: gatha.api
    ports:
      - "4000:4000"
    image: gatha-api
    volumes:
    - .:/usr/src/app
    - /usr/src/app/node_modules
    command: yarn start
    tty: true
    stdin_open: true
    network_mode: bridge
    depends_on:
      - gatha.db

  gatha.db:
    container_name: gatha.db
    # If running on Apple M1, use neo4j/neo4j-arm64-experimental:4.3.6-arm64
    image: neo4j:latest
    tty: true
    stdin_open: true
    network_mode: bridge
    ports:
      - "7687:7687"
      - "7474:7474"
    environment:
      - NEO4J_dbms_security_auth__enabled=false
      - NEO4J_dbms_default__listen__address=0.0.0.0
      - NEO4J_dbms_connector_bolt_listen__address=:7687
      - NEO4J_dbms_connector_bolt_advertised__address=:7687

